import { useState, type FormEvent } from 'react';
import { addDays, format } from 'date-fns';
import { toast } from 'sonner';
import type { Appointment, ClinicData } from '../../domain/types';
import { getService } from '../../services';
import { errorMessage, localDate, thaiDate } from '../../lib/format';
import { Modal } from '../../components/ui';
import { reservedSessions } from '../courses/CourseCards';
export function BookingForm({data,appointment,onClose,onSuccess,date:initialDate}:{data:ClinicData;appointment?:Appointment;onClose:()=>void;onSuccess:()=>Promise<void>;date:Date}) {
  const initial=appointment?new Date(appointment.start):initialDate<new Date()?addDays(new Date(),1):initialDate;
  const [customerId,setCustomerId]=useState(appointment?.customerId||data.customers[0]?.id||'');const [treatmentId,setTreatmentId]=useState(appointment?.treatmentId||data.treatments[0]?.id||'');const [practitionerId,setPractitionerId]=useState(appointment?.practitionerId||'s1');const [roomId,setRoomId]=useState(appointment?.roomId||'r1');const [date,setDate]=useState(localDate(initial));const [time,setTime]=useState(appointment?format(initial,'HH:mm'):'10:00');const [courseId,setCourseId]=useState(appointment?.courseId||'');const [error,setError]=useState('');const [busy,setBusy]=useState(false);
  const treatment=data.treatments.find(item=>item.id===treatmentId)!;const courses=data.courses.filter(item=>item.customerId===customerId&&item.treatmentId===treatmentId);
  async function submit(event:FormEvent){event.preventDefault();setError('');setBusy(true);try{await getService().book({customerId,treatmentId,practitionerId,roomId,start:new Date(date+'T'+time).toISOString(),courseId:courseId||undefined},appointment?.id);toast.success(appointment?'เลื่อนหรือแก้ไขคิวแล้ว':'บันทึกนัดหมายแล้ว');await onSuccess();onClose();}catch(error){setError(errorMessage(error));toast.error(errorMessage(error));}finally{setBusy(false);}}
  return <Modal title={appointment?'แก้ไข / เลื่อนนัดหมาย':'จองคิวใหม่'} open onClose={onClose}><form onSubmit={submit}><label>ลูกค้า<select value={customerId} onChange={event=>{setCustomerId(event.target.value);setCourseId('');}}>{data.customers.map(item=><option key={item.id} value={item.id}>{item.name} · {item.phone}</option>)}</select></label><label>บริการ<select value={treatmentId} onChange={event=>{setTreatmentId(event.target.value);setCourseId('');}}>{data.treatments.map(item=><option key={item.id} value={item.id}>{item.name} · {item.duration} นาที</option>)}</select></label><div className="form-grid"><label>ผู้ให้บริการ<select value={practitionerId} onChange={event=>setPractitionerId(event.target.value)}>{data.staff.filter(item=>item.kind!=='receptionist').map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>ห้องบริการ<select value={roomId} onChange={event=>setRoomId(event.target.value)}>{data.rooms.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>วันที่<input aria-label="วันที่นัดหมาย" type="date" value={date} onChange={event=>setDate(event.target.value)} required/></label><label>เวลาเริ่ม<input aria-label="เวลาเริ่มนัดหมาย" type="time" value={time} onChange={event=>setTime(event.target.value)} required/></label></div><label>ใช้คอร์สของลูกค้า<select value={courseId} onChange={event=>setCourseId(event.target.value)}><option value="">ไม่ใช้คอร์ส / ชำระแยก</option>{courses.map(item=><option key={item.id} value={item.id}>{item.remaining} ครั้ง · จองไว้ {reservedSessions(data,item.id)} · หมดอายุ {thaiDate(item.expiresAt)}</option>)}</select></label><p className="small muted">ใช้เวลา {treatment.duration} นาที · เปิดบริการ 10:00–20:00 · หักคอร์สเมื่อบริการเสร็จสิ้น</p>{error&&<p className="error" role="alert" data-testid="booking-warning">{error}</p>}<button className="button" disabled={busy}>{busy?'กำลังบันทึก':'บันทึกนัดหมาย'}</button></form></Modal>;
}