import { createRoot } from 'react-dom/client';
import { App } from './App';
import { configureService } from './services';
import { MockClinicService } from './services/mock';
import '@fontsource/sarabun/400.css';
import '@fontsource/sarabun/500.css';
import '@fontsource/sarabun/600.css';
import '@fontsource/sarabun/700.css';
import './styles.css';
configureService(new MockClinicService());
createRoot(document.getElementById('root')!).render(<App />);
